version: "3"

services:
  nginx:
    # image: renatobritto/rarify-nginx
    build: nginx
    networks:
      - internal
    depends_on:
      - front
    ports:
      - "80:80"

  front:
    # image: renatobritto/rarify-front
    container_name: front
    build: front
    volumes:
      - .:/front
    ports:
      - "3000:3000"
    networks:
      - internal
    depends_on:
      - back
    environment:
      - BACKEND_LOCATION=http://back:7000

  back:
    # image: renatobritto/rarify-back
    container_name: back
    build: back
    volumes:
      - .:/back
    ports:
      - "7000:7000"
    networks:
      - internal
    environment:
      - MONGO_DB=??

networks:
  internal:
    name: internal
